// Parity between the TypeScript evaluator and the Python model it was
// exported from (#114, epic #104).
//
// This is the main risk control for the whole export. The weights in
// `evaluatorModel.ts` were fitted against feature values computed by
// `fit_evaluator.py`; if `evaluator.ts` computes even slightly different
// numbers from the same 12 cards, the model is being applied to quantities it
// was never fitted against — and that failure is invisible. Nothing throws,
// nothing renders wrong, the AI just bids a bit differently forever and someone
// eventually notices the play is off. #118 is the precedent: two Base Bid
// constants were ported at half value, and what surfaced it was a parity check,
// not a player.
//
// `evaluatorParity.fixture.ts` is generated by `export_evaluator.py` from real
// auction situations in `rollout_dataset.csv`, and records what *Python*
// derived from each hand — the trump it named, the ceiling, every feature, the
// raw logit and the decision. Everything below is recomputed here from the 12
// cards alone and compared.

import { describe, expect, it } from 'vitest'
import { computeMaxBid } from './bidding'
import { Card, type CopyId, RANKS, type Rank, type Suit, SUITS } from './card'
import { evaluateBid, evaluateFold } from './evaluator'
import { BID_MODEL, FOLD_MODEL } from './evaluatorModel'
import { BID_PARITY_CASES, FOLD_PARITY_CASES } from './evaluatorParity.fixture'

/**
 * Inverse of Python's `Card.__repr__` / TS's `Card.toString()`: `10D_1` ->
 * the 10 of Diamonds, first copy. Kept local to this test rather than added to
 * `card.ts` — the app never parses cards back out of strings, only the fixture
 * does, and an engine API that exists solely for a test is API that will get
 * used somewhere it shouldn't.
 */
function parseHand(tokens: string): Card[] {
  return tokens.split(' ').map((token) => {
    const [body, copy] = token.split('_')
    const suit = body.slice(-1) as Suit
    const rank = body.slice(0, -1) as Rank
    if (!SUITS.includes(suit)) throw new Error(`bad suit in card token '${token}'`)
    if (!RANKS.includes(rank)) throw new Error(`bad rank in card token '${token}'`)
    return new Card(suit, rank, Number(copy) as CopyId)
  })
}

/** Python's logit to TS's, allowing only floating-point summation-order noise. */
const LOGIT_TOLERANCE = 1e-9

describe('the parity fixture itself', () => {
  // A fixture that only contained one verdict, or only landslide hands, would
  // pass every check below while proving nothing about the boundary — which is
  // the only place a small feature error can change a decision.
  it('covers both verdicts on both models', () => {
    for (const cases of [BID_PARITY_CASES, FOLD_PARITY_CASES]) {
      expect(cases.length).toBeGreaterThan(20)
      expect(cases.some((c) => c.decision === 1)).toBe(true)
      expect(cases.some((c) => c.decision === 0)).toBe(true)
    }
  })

  it('includes hands close enough to the boundary that a feature error would flip them', () => {
    const nearBoundary = BID_PARITY_CASES.filter((c) => Math.abs(c.logit) < 1)
    expect(nearBoundary.length).toBeGreaterThan(5)
  })

  it('records features in the exported model order', () => {
    expect(BID_MODEL.features).toHaveLength(BID_MODEL.weights.length)
    expect(FOLD_MODEL.features).toHaveLength(FOLD_MODEL.weights.length)
    for (const c of BID_PARITY_CASES) expect(c.features).toHaveLength(BID_MODEL.features.length)
    for (const c of FOLD_PARITY_CASES) expect(c.features).toHaveLength(FOLD_MODEL.features.length)
  })
})

describe('bid model parity with Python', () => {
  // Named separately from the feature sweep below because it is the one that
  // matters most: `base_bid_ceiling` is not a stored dataset column but a
  // re-derivation of `compute_max_bid` + `capped_bid`, it is worth about eight
  // points of decision agreement on its own (78.4% -> 86.3%), and it is
  // computed on the TS side by `bestBaseBid` — the same function whose ported
  // constants were wrong until #118.
  it('agrees on the trump and the base_bid_ceiling for every hand', () => {
    const mismatches = BID_PARITY_CASES.filter((c) => {
      const { trump, ceiling } = evaluateBid({
        hand: parseHand(c.hand),
        bid: c.bid,
        ourScore: c.ourScore,
        theirScore: c.theirScore,
        partnerHasBid: c.partnerHasBid === 1,
        partnerHasPassed: c.partnerHasPassed === 1,
      })
      return trump !== c.trump || ceiling !== c.ceiling
    }).map((c) => c.hand)
    expect(mismatches).toEqual([])
  })

  it('agrees on every feature, the logit and the decision', () => {
    for (const c of BID_PARITY_CASES) {
      const result = evaluateBid({
        hand: parseHand(c.hand),
        bid: c.bid,
        ourScore: c.ourScore,
        theirScore: c.theirScore,
        partnerHasBid: c.partnerHasBid === 1,
        partnerHasPassed: c.partnerHasPassed === 1,
      })
      // Compared per named feature rather than as one vector, so a failure
      // says *which* quantity diverged instead of dumping two number lists.
      BID_MODEL.features.forEach((name, i) => {
        expect(`${name}=${result.features[name]}`).toBe(`${name}=${c.features[i]}`)
      })
      expect(Math.abs(result.logit - c.logit)).toBeLessThan(LOGIT_TOLERANCE)
      expect(result.decision).toBe(c.decision === 1)
    }
  })
})

describe('fold model parity with Python', () => {
  it('agrees on the base_bid_ceiling, computed at 0/0 rather than the live score', () => {
    for (const c of FOLD_PARITY_CASES) {
      const hand = parseHand(c.hand)
      const trump = c.trump as Suit
      // Recomputed straight from the valuation functions, not read back out of
      // `evaluateFold`, so this check would still fail if `evaluateFold` were
      // changed to pass the live score into the competitive adjustment.
      expect(computeMaxBid(hand, trump, 0, 0).total).toBe(c.ceiling)
    }
  })

  it('agrees on every feature, the logit and the decision', () => {
    for (const c of FOLD_PARITY_CASES) {
      const result = evaluateFold({
        hand: parseHand(c.hand),
        trump: c.trump as Suit,
        bid: c.bid,
        biddingMeld: c.biddingMeld,
        defendingMeld: c.defendingMeld,
      })
      FOLD_MODEL.features.forEach((name, i) => {
        expect(`${name}=${result.features[name]}`).toBe(`${name}=${c.features[i]}`)
      })
      expect(Math.abs(result.logit - c.logit)).toBeLessThan(LOGIT_TOLERANCE)
      expect(result.decision).toBe(c.decision === 1)
    }
  })
})

describe('decision agreement overall', () => {
  // The headline number, asserted rather than printed. Agreement with the
  // *rollout* is 85.5%/92.0% and always will be — that is the distillation
  // loss #113 measured. Agreement with the *Python evaluator* has to be 100%:
  // it is the same arithmetic on the same features, and anything less is a
  // port bug, not a modelling limit.
  it('is exact on both models', () => {
    const bidAgreed = BID_PARITY_CASES.filter(
      (c) =>
        evaluateBid({
          hand: parseHand(c.hand),
          bid: c.bid,
          ourScore: c.ourScore,
          theirScore: c.theirScore,
          partnerHasBid: c.partnerHasBid === 1,
          partnerHasPassed: c.partnerHasPassed === 1,
        }).decision === (c.decision === 1),
    ).length
    expect(bidAgreed).toBe(BID_PARITY_CASES.length)

    const foldAgreed = FOLD_PARITY_CASES.filter(
      (c) =>
        evaluateFold({
          hand: parseHand(c.hand),
          trump: c.trump as Suit,
          bid: c.bid,
          biddingMeld: c.biddingMeld,
          defendingMeld: c.defendingMeld,
        }).decision === (c.decision === 1),
    ).length
    expect(foldAgreed).toBe(FOLD_PARITY_CASES.length)
  })
})
