// Parity between `chooseFollowCard` and the Python follower it was ported from,
// position by position (#319).
//
// `engineParity.test.ts` replays Python-recorded rounds through this engine,
// but it plays the recorded cards as INPUTS — it never asks whether this engine
// would have chosen them. So when #312 forked `chooseFollowCard` on who led the
// trick, TypeScript only, every suite stayed green; it was found by reading and
// reverted in #317. Feed-ahead (#316) and the protecting sluff (#318) were then
// hand-ported into both engines with nothing comparing the two. This file is
// that comparison.
//
// `followParity.fixture.ts` is generated by `export_follow_parity.py` and
// records what *Python's* `choose_follow_card` plays at each position. Every
// position is replayed here from its hand, legal set, trick and the cards seen
// so far, through `chooseFollowCard` with a `PlayTracker` rebuilt from the same
// cards. The legal set is also re-derived with `Trick.legalMoves`, so the
// position cannot be one this engine's rules would not produce.
//
// ONE DELIBERATE DIVERGENCE, and it is excluded by name rather than by silence:
// #158's safe-counter selection (`safeCounterPolicy: 'counted'`). Forced to
// beat with nothing but counters while a seat is still to play, this engine
// spends the cheapest counter that cannot itself be beaten in suit; forced to
// overtrump it does the same in trump. Python spends the lowest. It is a
// TypeScript-measured addition that Paul kept when #312 was reverted
// (web/README.md, "#312 reverted"), and Python has no counterpart. So:
//
//   1. Every position is replayed with `safeCounterPolicy: 'off'` — every other
//      field the shipped one — and must agree with Python exactly. That is the
//      whole port, #158 aside.
//   2. Every position is replayed with the shipped configuration, and may
//      disagree ONLY at a position where #158's tier can fire. Anything else
//      is drift.
//
// `TrumpMemory` is not passed: the shipped game gives each seat a capacity-10
// memory, which only #158's tier consults. Without one, trump questions read
// the exact tracker — the reading Python has.
//
// NOT covered, and it cannot be: Python's expert follow
// (`choose_expert_follow_card`), which has no TypeScript port.

import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { Card, type CopyId, RANKS, type Rank, type Suit, SUITS } from './card'
import { FOLLOW_PARITY_BRANCHES, FOLLOW_PARITY_SCENARIOS, type FollowParityScenario } from './followParity.fixture'
import { SHIPPED_PARAMS, SHIPPED_SKILL, SKILL_PARAMS, type SkillParams } from './skills'
import { chooseFollowCard, PlayTracker } from './tracker'
import { POINT_RANKS, Trick, type PlayerIndex, type TrickPlay } from './trick'

/** Inverse of `Card.toString()`. Local to the test for the reason
 *  `passParity.test.ts` gives: only fixtures parse cards back out of strings. */
function parseCard(token: string): Card {
  const [body, copy] = token.split('_')
  const suit = body.slice(-1) as Suit
  const rank = body.slice(0, -1) as Rank
  if (!SUITS.includes(suit)) throw new Error(`bad suit in card token '${token}'`)
  if (!RANKS.includes(rank)) throw new Error(`bad rank in card token '${token}'`)
  return new Card(suit, rank, Number(copy) as CopyId)
}

function parseCards(tokens: string): Card[] {
  return tokens === '' ? [] : tokens.split(' ').map(parseCard)
}

function parseTrick(tokens: string): TrickPlay[] {
  return tokens.split(' ').map((item) => {
    const [seat, card] = item.split(':')
    return { player: Number(seat) as PlayerIndex, card: parseCard(card) }
  })
}

interface Position {
  readonly hand: Card[]
  readonly legal: Card[]
  readonly plays: TrickPlay[]
  readonly tracker: PlayTracker
}

function position(s: FollowParityScenario): Position {
  const tracker = new PlayTracker()
  for (const card of parseCards(s.played)) tracker.record(card)
  return { hand: parseCards(s.hand), legal: parseCards(s.legal), plays: parseTrick(s.trick), tracker }
}

function follow(s: FollowParityScenario): string {
  const p = position(s)
  return chooseFollowCard(p.hand, p.legal, p.plays, s.trump, s.team, p.tracker, SHIPPED_SKILL).toString()
}

function describeScenario(s: FollowParityScenario): string {
  return `${s.id} [${s.branch}, ${s.ledBy} led] trick ${s.trick}; legal ${s.legal} — ${s.covers}`
}

/**
 * Whether #158 can change the card at this position — the only place the
 * shipped configuration is allowed to leave Python. Mirrors the two places
 * `chooseFollowCard` reads `counted`:
 *
 *   - A forced OVERTRUMP (a trump already winning, every legal card a trump
 *     that beats it). Python has no such tier: it answers with its
 *     discretionary trump rule (unsecured -> the lowest *point* trump). #158
 *     routes it to `chooseForcedBeat` instead — a non-counter first, then the
 *     cheapest counter nothing in trump can beat. So this whole position class
 *     is #158's, counters or not.
 *   - A forced beat in a side lead suit with every legal card a counter and a
 *     seat still to play. Anywhere else in that branch `chooseForcedBeat`
 *     reduces to Python's "lowest legal card" (a non-counter if one is legal;
 *     the lowest counter in the last seat). Feed-ahead is decided before it,
 *     so a feed-ahead position never gets here.
 */
function safeCounterCanFire(s: FollowParityScenario): boolean {
  if (s.branch === 'feed_ahead') return false
  const p = position(s)
  const trumpPlays = p.plays.filter((t) => t.card.suit === s.trump)
  const leadSuit = p.plays[0].card.suit
  const pool = trumpPlays.length > 0 ? trumpPlays : p.plays.filter((t) => t.card.suit === leadSuit)
  const winner = pool.reduce((best, t) => (t.card.rankValue > best.card.rankValue ? t : best)).card
  if (!p.legal.every((c) => c.beats(winner, s.trump))) return false

  const overtrump = winner.suit === s.trump && p.legal.every((c) => c.suit === s.trump)
  if (overtrump) return true

  const sideSuitBeat = leadSuit !== s.trump && p.legal.every((c) => c.suit === leadSuit)
  return sideSuitBeat && p.plays.length < 3 && p.legal.every((c) => POINT_RANKS.has(c.rank))
}

/** Install `params` on the shipped slot for one block, restoring after — the
 *  `installPolicies` seam (`ab/abRun.ts`), narrowed to the one level read. */
function withParams(params: SkillParams): void {
  let saved: SkillParams
  beforeAll(() => {
    saved = SKILL_PARAMS[SHIPPED_SKILL]
    SKILL_PARAMS[SHIPPED_SKILL] = params
  })
  afterAll(() => {
    SKILL_PARAMS[SHIPPED_SKILL] = saved
  })
}

describe('the follow parity fixture itself', () => {
  it('carries dealt and built positions, enough of them', () => {
    const sources = new Set(FOLLOW_PARITY_SCENARIOS.map((s) => s.source))
    expect(sources).toEqual(new Set(['deal', 'built']))
    expect(FOLLOW_PARITY_SCENARIOS.length).toBeGreaterThanOrEqual(200)
  })

  it('reaches every tier, and the shared ones after both an opponent’s lead and partner’s', () => {
    const seen = new Set(FOLLOW_PARITY_SCENARIOS.map((s) => `${s.branch}/${s.ledBy}`))
    for (const branch of FOLLOW_PARITY_BRANCHES) {
      // Feed-ahead is an opponent's lead by definition; everything else can
      // follow either side's lead and #312 forked on exactly that.
      const sides = branch === 'feed_ahead' ? ['opponent'] : ['opponent', 'partner']
      for (const side of sides) {
        expect(seen.has(`${branch}/${side}`), `${branch} after ${side}'s lead`).toBe(true)
      }
    }
  })

  it('records only positions this engine’s rules produce', () => {
    for (const s of FOLLOW_PARITY_SCENARIOS) {
      const p = position(s)
      const trick = new Trick(s.trump)
      for (const play of p.plays) trick.play(play.player, play.card)
      const legal = trick.legalMoves(p.hand).map((c) => c.toString())
      expect(legal, s.id).toEqual(p.legal.map((c) => c.toString()))
      expect(legal.length, s.id).toBeGreaterThan(1)
      expect(legal, s.id).toContain(s.chosen)
    }
  })
})

describe('chooseFollowCard plays what Python plays (safe counters off — Python’s rule)', () => {
  withParams({ ...SHIPPED_PARAMS, safeCounterPolicy: 'off' })

  it('agrees at every recorded position', () => {
    const disagreements = FOLLOW_PARITY_SCENARIOS.filter((s) => follow(s) !== s.chosen).map(
      (s) => `${describeScenario(s)}: Python ${s.chosen}, TS ${follow(s)}`,
    )
    expect(disagreements).toEqual([])
  })
})

describe('the shipped chooseFollowCard leaves Python only where #158 says it does', () => {
  withParams(SHIPPED_PARAMS)

  it('agrees at every position #158’s tier cannot reach', () => {
    const drift = FOLLOW_PARITY_SCENARIOS.filter((s) => !safeCounterCanFire(s) && follow(s) !== s.chosen).map(
      (s) => `${describeScenario(s)}: Python ${s.chosen}, TS ${follow(s)}`,
    )
    expect(drift).toEqual([])
  })

  it('does part from Python at the built #158 positions, so the exclusion is not vacuous', () => {
    // b10 (in suit) and b13 (in trump): every legal card a counter, the Ace
    // among them and a seat still to play. Python spends the King; the shipped
    // rule spends the Ace, the one counter nothing in suit can beat.
    for (const id of ['b10', 'b13']) {
      const s = FOLLOW_PARITY_SCENARIOS.find((x) => x.id === id) as FollowParityScenario
      expect(safeCounterCanFire(s), id).toBe(true)
      expect(s.chosen.startsWith('K'), id).toBe(true)
      expect(follow(s).startsWith('A'), id).toBe(true)
    }
  })
})
