// Parity between this engine's 3-card pass and the Python passer it was ported
// from (#279).
//
// `engineParity.test.ts` replays Python-recorded rounds through this engine and
// checks the meld, every trick winner and the round score — but it takes the
// recorded pass as an INPUT. It moves the three cards Python moved and grades
// what follows; it never asks whether this engine would have chosen those three
// cards. #276 moved two of its forty recorded passes and #280 moved seventeen,
// twelve of them changing a round score, and the suite was green throughout.
// Correctly so: both engines moved together. Nothing would have said if only one
// had, and pass selection is the largest hand-ported surface in `web/src/engine/`
// — two nine-tier priority lists with several predicates each, plus the D/S vs
// H/C category split on top.
//
// `passParity.fixture.ts` is generated by `export_pass_parity.py` and records
// what *Python* sent from each hand. Everything below is recomputed here from
// the twelve cards, the trump suit and the role alone.
//
// COMPARED AS A SET. The tiers build an ordered selection, but
// `Round._passing_phase` moves all three cards at once and nothing downstream
// can tell which tier produced which — so an order-only disagreement is not a
// bug this suite should fail on, and a set comparison is the one that survives
// a tie-break resolved differently. It gives up nothing that matters: any tier
// change that swaps *which* card is chosen changes the set.
//
// Two entry points are checked per scenario, deliberately:
//
//   The tier function directly (`partnerPassSelection` / `bidderPassSelection`)
//   with Python's recorded category, which isolates the tiers.
//
//   `choosePassCards`, which is what the browser actually calls, and which
//   derives the category from the trump suit using its own copy of the D/S vs
//   H/C rule. That copy is a ported one-line constant of exactly #118's kind —
//   it would be invisible on its own, and it flips the whole priority list.
//
// NOT covered, and it cannot be: Python's expert-tier pass logic
// (`choose_forward_pass_cards` and the knapsack `choose_return_pass_cards`,
// issue #61). There is no TypeScript counterpart to compare against — that code
// is unported, not merely untested. Nor `choosePassCards`'s `meld_only` arm,
// which has a Python counterpart (`EasyPlayer`) but is unreachable in the
// browser, since `SHIPPED_SKILL` is `base_bid`.

import { describe, expect, it } from 'vitest'
import { Card, type CopyId, RANKS, type Rank, type Suit, SUITS } from './card'
import { PASS_COUNT, bidderPassSelection, choosePassCards, partnerPassSelection } from './passing'
import { PASS_PARITY_PASS_COUNT, PASS_PARITY_SCENARIOS } from './passParity.fixture'

/**
 * Inverse of Python's `Card.__repr__` / this side's `Card.toString()`: `10D_1`
 * -> the 10 of Diamonds, first copy. Kept local to this test for the reason
 * `evaluatorParity.test.ts` gives — the app never parses cards back out of
 * strings, only fixtures do, and an engine API that exists solely for a test is
 * API that will get used somewhere it shouldn't.
 */
function parseHand(tokens: string): Card[] {
  return tokens.split(' ').map((token) => {
    const [body, copy] = token.split('_')
    const suit = body.slice(-1) as Suit
    const rank = body.slice(0, -1) as Rank
    if (!SUITS.includes(suit)) throw new Error(`bad suit in card token '${token}'`)
    if (!RANKS.includes(rank)) throw new Error(`bad rank in card token '${token}'`)
    return new Card(suit, rank, Number(copy) as CopyId)
  })
}

function tokenSet(cards: readonly Card[]): Set<string> {
  return new Set(cards.map((c) => c.toString()))
}

/** Sorted for the failure message: `expect(...).toEqual` on a Set prints the
 *  two sets, and reading which card moved is the whole point of hitting this. */
function sortedTokens(tokens: Iterable<string>): string[] {
  return [...tokens].sort()
}

describe('the pass parity fixture itself', () => {
  it('carries both dealt and deliberately built hands', () => {
    // Dealt hands are unbiased and are where the tie-breaks live; they also stop
    // in the first tier or two almost every time, so a fixture of nothing but
    // dealt hands would look like coverage while leaving most of both priority
    // lists untouched.
    const sources = new Set(PASS_PARITY_SCENARIOS.map((s) => s.source))
    expect(sources).toEqual(new Set(['deal', 'built']))
    expect(PASS_PARITY_SCENARIOS.filter((s) => s.source === 'built').length).toBeGreaterThanOrEqual(10)
    expect(PASS_PARITY_SCENARIOS.length).toBeGreaterThanOrEqual(40)
  })

  it('covers both roles, both categories and all four trump suits', () => {
    expect(new Set(PASS_PARITY_SCENARIOS.map((s) => s.role))).toEqual(new Set(['bidder', 'partner']))
    expect(new Set(PASS_PARITY_SCENARIOS.map((s) => s.category))).toEqual(new Set(['DS', 'HC']))
    expect(new Set(PASS_PARITY_SCENARIOS.map((s) => s.trump))).toEqual(new Set(SUITS))
  })

  it('agrees with this engine on how many cards a pass moves', () => {
    // PASS_COUNT is a rule, not strategy (pinochle_rules.md), and it is the one
    // number in `passing.ts` that Python is flatly authoritative for.
    expect(PASS_PARITY_PASS_COUNT).toBe(PASS_COUNT)
  })

  it('records twelve distinct cards and three of them passed, every time', () => {
    for (const scenario of PASS_PARITY_SCENARIOS) {
      const hand = parseHand(scenario.hand)
      const passed = parseHand(scenario.passed)
      expect(tokenSet(hand).size, scenario.id).toBe(12)
      expect(tokenSet(passed).size, scenario.id).toBe(PASS_COUNT)
      for (const token of tokenSet(passed)) {
        expect(tokenSet(hand).has(token), `${scenario.id}: ${token} is not in the hand`).toBe(true)
      }
    }
  })
})

describe('this engine sends what Python sent', () => {
  it('chooses the same three cards from every recorded hand', () => {
    for (const scenario of PASS_PARITY_SCENARIOS) {
      const hand = parseHand(scenario.hand)
      const select = scenario.role === 'bidder' ? bidderPassSelection : partnerPassSelection
      const chosen = select(hand, scenario.trump, scenario.category, PASS_COUNT)

      expect(chosen.length, scenario.id).toBe(PASS_COUNT)
      expect(
        sortedTokens(tokenSet(chosen)),
        `${scenario.id} (${scenario.role}, ${scenario.trump}, ${scenario.category}) — ${scenario.covers}`,
      ).toEqual(sortedTokens(scenario.passed.split(' ')))
    }
  })

  it('reaches the same answer through choosePassCards, deriving the category itself', () => {
    // The shipped path. `choosePassCards` picks D/S vs H/C from the trump suit
    // and then dispatches, so this covers the split as well as the tiers — and
    // a wrong split silently swaps the entire priority list for two of the four
    // trump suits, which is the shape of #118.
    for (const scenario of PASS_PARITY_SCENARIOS) {
      const hand = parseHand(scenario.hand)
      const chosen = choosePassCards(hand, PASS_COUNT, scenario.trump, scenario.role === 'bidder')
      expect(sortedTokens(tokenSet(chosen)), `${scenario.id} via choosePassCards`).toEqual(
        sortedTokens(scenario.passed.split(' ')),
      )
    }
  })

  it('takes the pass out of the hand it was given and leaves the rest', () => {
    // Cheap, and it is the property `engineParity.fixture.ts` relies on when it
    // rebuilds post-pass hands: a passer that duplicated a card or invented one
    // would corrupt a round rather than merely misplay it.
    for (const scenario of PASS_PARITY_SCENARIOS) {
      const hand = parseHand(scenario.hand)
      const select = scenario.role === 'bidder' ? bidderPassSelection : partnerPassSelection
      const chosen = select(hand, scenario.trump, scenario.category, PASS_COUNT)
      expect(tokenSet(chosen).size, scenario.id).toBe(PASS_COUNT)
      for (const card of chosen) {
        expect(tokenSet(hand).has(card.toString()), scenario.id).toBe(true)
      }
      expect(hand.length, `${scenario.id}: the passer must not mutate its input`).toBe(12)
    }
  })
})
